{
  "home":{
    "max_ram":131072,
    "free_ram":117415.50000000291,
    "ram_slices":{
      "1":{},
      "4139":{},
      "4142":{},
      "4143":{},
      "4148":{},
      "4153":{},
      "4158":{},
      "4167":{},
      "4180":{},
      "4193":{},
      "4210":{},
      "4239":{},
      "4272":{},
      "4313":{},
      "4358":{},
      "4407":{},
      "4460":{},
      "4517":{},
      "4604":{},
      "4669":{},
      "4738":{},
      "4811":{},
      "4908":{},
      "6771":{},
      "7914":{},
      "7975":{},
      "-1":{},
    },
  },
  "n00dles":{
    "max_ram":4,
    "free_ram":4,
    "ram_slices":{
    },
  },
  "foodnstuff":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "max-hardware":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "neo-net":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "netlink":{
    "max_ram":128,
    "free_ram":128,
    "ram_slices":{
    },
  },
  "rothman-uni":{
    "max_ram":64,
    "free_ram":64,
    "ram_slices":{
    },
  },
  "catalyst":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "silver-helix":{
    "max_ram":64,
    "free_ram":64,
    "ram_slices":{
    },
  },
  "phantasy":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "the-hub":{
    "max_ram":64,
    "free_ram":64,
    "ram_slices":{
    },
  },
  "syscore":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "avmnite-02h":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "sigma-cosmetics":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "joesguns":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "nectar-net":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "CSEC":{
    "max_ram":8,
    "free_ram":8,
    "ram_slices":{
    },
  },
  "omega-net":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "computek":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "summit-uni":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "I.I.I.I":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "rho-construction":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "alpha-ent":{
    "max_ram":64,
    "free_ram":64,
    "ram_slices":{
    },
  },
  "aerocorp":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "aevum-police":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "millenium-fitness":{
    "max_ram":64,
    "free_ram":64,
    "ram_slices":{
    },
  },
  "global-pharm":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "johnson-ortho":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "zb-institute":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "lexo-corp":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "galactic-cyber":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "omnia":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "deltaone":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "univ-energy":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "infocomm":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "titan-labs":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "microdyne":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "stormtech":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "4sigma":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "powerhouse-fitness":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "fulcrumassets":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "kuai-gong":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "b-and-a":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  ".":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "blade":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "megacorp":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "helios":{
    "max_ram":256,
    "free_ram":256,
    "ram_slices":{
    },
  },
  "omnitek":{
    "max_ram":256,
    "free_ram":256,
    "ram_slices":{
    },
  },
  "nwo":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "ecorp":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "The-Cave":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "clarkinc":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "vitalife":{
    "max_ram":64,
    "free_ram":64,
    "ram_slices":{
    },
  },
  "applied-energetics":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "fulcrumtech":{
    "max_ram":512,
    "free_ram":512,
    "ram_slices":{
    },
  },
  "run4theh111z":{
    "max_ram":256,
    "free_ram":256,
    "ram_slices":{
    },
  },
  "zb-def":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "snap-fitness":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "unitalife":{
    "max_ram":64,
    "free_ram":64,
    "ram_slices":{
    },
  },
  "defcomm":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "nova-med":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "icarus":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "solaris":{
    "max_ram":128,
    "free_ram":128,
    "ram_slices":{
    },
  },
  "taiyang-digital":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "zeus-med":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "crush-fitness":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "hong-fang-tea":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "harakiri-sushi":{
    "max_ram":16,
    "free_ram":16,
    "ram_slices":{
    },
  },
  "iron-gym":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "zer0":{
    "max_ram":32,
    "free_ram":32,
    "ram_slices":{
    },
  },
  "pserv-0":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-1":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-2":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-3":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-4":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-5":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-6":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-7":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-8":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-9":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-10":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-11":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-12":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-13":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-14":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-15":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-16":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-17":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-18":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-19":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-20":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-21":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-22":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-23":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "pserv-24":{
    "max_ram":1048576,
    "free_ram":524288,
    "ram_slices":{
    },
  },
  "darkweb":{
    "max_ram":0,
    "free_ram":0,
    "ram_slices":{
    },
  },
  "total_ram":{
    "max_ram":undefined,
    "free_ram":undefined,
    "ram_slices":{
    },
  },
}